//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Process_APP_Desk.ServiceProcess_Cargo {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProcess_Cargo.Process_CargoSoap")]
    public interface Process_CargoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCargoConEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertarCargoConEntidad_Escritorio(System.Data.DataSet _unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCargoConEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertarCargoConEntidad_EscritorioAsync(System.Data.DataSet _unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCargoSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertarCargoSinEntidad_Escritorio(string _nombre, string _descripcion, string _rut_empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCargoSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertarCargoSinEntidad_EscritorioAsync(string _nombre, string _descripcion, string _rut_empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCargoConEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ActualizarCargoConEntidad_Escritorio(System.Data.DataSet _unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCargoConEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ActualizarCargoConEntidad_EscritorioAsync(System.Data.DataSet _unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCargoSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ActualizarCargoSinEntidad_Escritorio(int _id_cargo, string _nombre, string _descripcion, string _rut_empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCargoSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ActualizarCargoSinEntidad_EscritorioAsync(int _id_cargo, string _nombre, string _descripcion, string _rut_empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCargoSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerCargoSinEntidad_Escritorio(int _id_cargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCargoSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerCargoSinEntidad_EscritorioAsync(int _id_cargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCargoConEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Process_APP_Desk.ServiceProcess_Cargo.Cargo TraerCargoConEntidad_Escritorio(int _id_cargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCargoConEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_Cargo.Cargo> TraerCargoConEntidad_EscritorioAsync(int _id_cargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCargoConEmpresaSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerCargoConEmpresaSinEntidad_Escritorio(string _rut_empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCargoConEmpresaSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerCargoConEmpresaSinEntidad_EscritorioAsync(string _rut_empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCargoConEmpresaConEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Process_APP_Desk.ServiceProcess_Cargo.Cargo TraerCargoConEmpresaConEntidad_Escritorio(string _rut_empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCargoConEmpresaConEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_Cargo.Cargo> TraerCargoConEmpresaConEntidad_EscritorioAsync(string _rut_empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCargoPorNombrePorEmpresaConEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Process_APP_Desk.ServiceProcess_Cargo.Cargo TraerCargoPorNombrePorEmpresaConEntidad_Escritorio(string _nombre, string _rut_empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCargoPorNombrePorEmpresaConEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_Cargo.Cargo> TraerCargoPorNombrePorEmpresaConEntidad_EscritorioAsync(string _nombre, string _rut_empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCargoConClaveSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerCargoConClaveSinEntidad_Escritorio(string _palabra_clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCargoConClaveSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerCargoConClaveSinEntidad_EscritorioAsync(string _palabra_clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerTodasCargos_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerTodasCargos_Escritorio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerTodasCargos_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerTodasCargos_EscritorioAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cargo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_cargoField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string rut_empresaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id_cargo {
            get {
                return this.id_cargoField;
            }
            set {
                this.id_cargoField = value;
                this.RaisePropertyChanged("Id_cargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Rut_empresa {
            get {
                return this.rut_empresaField;
            }
            set {
                this.rut_empresaField = value;
                this.RaisePropertyChanged("Rut_empresa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Process_CargoSoapChannel : Process_APP_Desk.ServiceProcess_Cargo.Process_CargoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Process_CargoSoapClient : System.ServiceModel.ClientBase<Process_APP_Desk.ServiceProcess_Cargo.Process_CargoSoap>, Process_APP_Desk.ServiceProcess_Cargo.Process_CargoSoap {
        
        public Process_CargoSoapClient() {
        }
        
        public Process_CargoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Process_CargoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_CargoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_CargoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertarCargoConEntidad_Escritorio(System.Data.DataSet _unidad) {
            return base.Channel.InsertarCargoConEntidad_Escritorio(_unidad);
        }
        
        public System.Threading.Tasks.Task<int> InsertarCargoConEntidad_EscritorioAsync(System.Data.DataSet _unidad) {
            return base.Channel.InsertarCargoConEntidad_EscritorioAsync(_unidad);
        }
        
        public int InsertarCargoSinEntidad_Escritorio(string _nombre, string _descripcion, string _rut_empresa) {
            return base.Channel.InsertarCargoSinEntidad_Escritorio(_nombre, _descripcion, _rut_empresa);
        }
        
        public System.Threading.Tasks.Task<int> InsertarCargoSinEntidad_EscritorioAsync(string _nombre, string _descripcion, string _rut_empresa) {
            return base.Channel.InsertarCargoSinEntidad_EscritorioAsync(_nombre, _descripcion, _rut_empresa);
        }
        
        public int ActualizarCargoConEntidad_Escritorio(System.Data.DataSet _unidad) {
            return base.Channel.ActualizarCargoConEntidad_Escritorio(_unidad);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarCargoConEntidad_EscritorioAsync(System.Data.DataSet _unidad) {
            return base.Channel.ActualizarCargoConEntidad_EscritorioAsync(_unidad);
        }
        
        public int ActualizarCargoSinEntidad_Escritorio(int _id_cargo, string _nombre, string _descripcion, string _rut_empresa) {
            return base.Channel.ActualizarCargoSinEntidad_Escritorio(_id_cargo, _nombre, _descripcion, _rut_empresa);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarCargoSinEntidad_EscritorioAsync(int _id_cargo, string _nombre, string _descripcion, string _rut_empresa) {
            return base.Channel.ActualizarCargoSinEntidad_EscritorioAsync(_id_cargo, _nombre, _descripcion, _rut_empresa);
        }
        
        public System.Data.DataSet TraerCargoSinEntidad_Escritorio(int _id_cargo) {
            return base.Channel.TraerCargoSinEntidad_Escritorio(_id_cargo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerCargoSinEntidad_EscritorioAsync(int _id_cargo) {
            return base.Channel.TraerCargoSinEntidad_EscritorioAsync(_id_cargo);
        }
        
        public Process_APP_Desk.ServiceProcess_Cargo.Cargo TraerCargoConEntidad_Escritorio(int _id_cargo) {
            return base.Channel.TraerCargoConEntidad_Escritorio(_id_cargo);
        }
        
        public System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_Cargo.Cargo> TraerCargoConEntidad_EscritorioAsync(int _id_cargo) {
            return base.Channel.TraerCargoConEntidad_EscritorioAsync(_id_cargo);
        }
        
        public System.Data.DataSet TraerCargoConEmpresaSinEntidad_Escritorio(string _rut_empresa) {
            return base.Channel.TraerCargoConEmpresaSinEntidad_Escritorio(_rut_empresa);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerCargoConEmpresaSinEntidad_EscritorioAsync(string _rut_empresa) {
            return base.Channel.TraerCargoConEmpresaSinEntidad_EscritorioAsync(_rut_empresa);
        }
        
        public Process_APP_Desk.ServiceProcess_Cargo.Cargo TraerCargoConEmpresaConEntidad_Escritorio(string _rut_empresa) {
            return base.Channel.TraerCargoConEmpresaConEntidad_Escritorio(_rut_empresa);
        }
        
        public System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_Cargo.Cargo> TraerCargoConEmpresaConEntidad_EscritorioAsync(string _rut_empresa) {
            return base.Channel.TraerCargoConEmpresaConEntidad_EscritorioAsync(_rut_empresa);
        }
        
        public Process_APP_Desk.ServiceProcess_Cargo.Cargo TraerCargoPorNombrePorEmpresaConEntidad_Escritorio(string _nombre, string _rut_empresa) {
            return base.Channel.TraerCargoPorNombrePorEmpresaConEntidad_Escritorio(_nombre, _rut_empresa);
        }
        
        public System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_Cargo.Cargo> TraerCargoPorNombrePorEmpresaConEntidad_EscritorioAsync(string _nombre, string _rut_empresa) {
            return base.Channel.TraerCargoPorNombrePorEmpresaConEntidad_EscritorioAsync(_nombre, _rut_empresa);
        }
        
        public System.Data.DataSet TraerCargoConClaveSinEntidad_Escritorio(string _palabra_clave) {
            return base.Channel.TraerCargoConClaveSinEntidad_Escritorio(_palabra_clave);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerCargoConClaveSinEntidad_EscritorioAsync(string _palabra_clave) {
            return base.Channel.TraerCargoConClaveSinEntidad_EscritorioAsync(_palabra_clave);
        }
        
        public System.Data.DataSet TraerTodasCargos_Escritorio() {
            return base.Channel.TraerTodasCargos_Escritorio();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerTodasCargos_EscritorioAsync() {
            return base.Channel.TraerTodasCargos_EscritorioAsync();
        }
    }
}
