//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Process_APP_Desk.ServiceProcess_Rol {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProcess_Rol.Process_RolSoap")]
    public interface Process_RolSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarRolConEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertarRolConEntidad_Escritorio(System.Data.DataSet _unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarRolConEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertarRolConEntidad_EscritorioAsync(System.Data.DataSet _unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarRolSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertarRolSinEntidad_Escritorio(string _nombre, int _estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarRolSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertarRolSinEntidad_EscritorioAsync(string _nombre, int _estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarRolConEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ActualizarRolConEntidad_Escritorio(System.Data.DataSet _unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarRolConEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ActualizarRolConEntidad_EscritorioAsync(System.Data.DataSet _unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarRolSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ActualizarRolSinEntidad_Escritorio(int _id_rol, string _nombre, int _estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarRolSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ActualizarRolSinEntidad_EscritorioAsync(int _id_rol, string _nombre, int _estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerRolSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerRolSinEntidad_Escritorio(int _id_rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerRolSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerRolSinEntidad_EscritorioAsync(int _id_rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerRolConEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Process_APP_Desk.ServiceProcess_Rol.Rol TraerRolConEntidad_Escritorio(int _id_rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerRolConEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_Rol.Rol> TraerRolConEntidad_EscritorioAsync(int _id_rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerTodasRoles_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerTodasRoles_Escritorio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerTodasRoles_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerTodasRoles_EscritorioAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Rol : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_rolField;
        
        private string nombreField;
        
        private int estadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id_rol {
            get {
                return this.id_rolField;
            }
            set {
                this.id_rolField = value;
                this.RaisePropertyChanged("Id_rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Process_RolSoapChannel : Process_APP_Desk.ServiceProcess_Rol.Process_RolSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Process_RolSoapClient : System.ServiceModel.ClientBase<Process_APP_Desk.ServiceProcess_Rol.Process_RolSoap>, Process_APP_Desk.ServiceProcess_Rol.Process_RolSoap {
        
        public Process_RolSoapClient() {
        }
        
        public Process_RolSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Process_RolSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_RolSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_RolSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertarRolConEntidad_Escritorio(System.Data.DataSet _unidad) {
            return base.Channel.InsertarRolConEntidad_Escritorio(_unidad);
        }
        
        public System.Threading.Tasks.Task<int> InsertarRolConEntidad_EscritorioAsync(System.Data.DataSet _unidad) {
            return base.Channel.InsertarRolConEntidad_EscritorioAsync(_unidad);
        }
        
        public int InsertarRolSinEntidad_Escritorio(string _nombre, int _estado) {
            return base.Channel.InsertarRolSinEntidad_Escritorio(_nombre, _estado);
        }
        
        public System.Threading.Tasks.Task<int> InsertarRolSinEntidad_EscritorioAsync(string _nombre, int _estado) {
            return base.Channel.InsertarRolSinEntidad_EscritorioAsync(_nombre, _estado);
        }
        
        public int ActualizarRolConEntidad_Escritorio(System.Data.DataSet _unidad) {
            return base.Channel.ActualizarRolConEntidad_Escritorio(_unidad);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarRolConEntidad_EscritorioAsync(System.Data.DataSet _unidad) {
            return base.Channel.ActualizarRolConEntidad_EscritorioAsync(_unidad);
        }
        
        public int ActualizarRolSinEntidad_Escritorio(int _id_rol, string _nombre, int _estado) {
            return base.Channel.ActualizarRolSinEntidad_Escritorio(_id_rol, _nombre, _estado);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarRolSinEntidad_EscritorioAsync(int _id_rol, string _nombre, int _estado) {
            return base.Channel.ActualizarRolSinEntidad_EscritorioAsync(_id_rol, _nombre, _estado);
        }
        
        public System.Data.DataSet TraerRolSinEntidad_Escritorio(int _id_rol) {
            return base.Channel.TraerRolSinEntidad_Escritorio(_id_rol);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerRolSinEntidad_EscritorioAsync(int _id_rol) {
            return base.Channel.TraerRolSinEntidad_EscritorioAsync(_id_rol);
        }
        
        public Process_APP_Desk.ServiceProcess_Rol.Rol TraerRolConEntidad_Escritorio(int _id_rol) {
            return base.Channel.TraerRolConEntidad_Escritorio(_id_rol);
        }
        
        public System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_Rol.Rol> TraerRolConEntidad_EscritorioAsync(int _id_rol) {
            return base.Channel.TraerRolConEntidad_EscritorioAsync(_id_rol);
        }
        
        public System.Data.DataSet TraerTodasRoles_Escritorio() {
            return base.Channel.TraerTodasRoles_Escritorio();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerTodasRoles_EscritorioAsync() {
            return base.Channel.TraerTodasRoles_EscritorioAsync();
        }
    }
}
