//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Process_APP_Desk.ServiceProcess_Acceso {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProcess_Acceso.Process_AccesoSoap")]
    public interface Process_AccesoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerAccesoSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerAccesoSinEntidad_Escritorio(int _id_acceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerAccesoSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerAccesoSinEntidad_EscritorioAsync(int _id_acceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerAccesoConEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Process_APP_Desk.ServiceProcess_Acceso.Acceso TraerAccesoConEntidad_Escritorio(int _id_acceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerAccesoConEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_Acceso.Acceso> TraerAccesoConEntidad_EscritorioAsync(int _id_acceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerTodasAccesos_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerTodasAccesos_Escritorio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerTodasAccesos_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerTodasAccesos_EscritorioAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Acceso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_accesoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id_acceso {
            get {
                return this.id_accesoField;
            }
            set {
                this.id_accesoField = value;
                this.RaisePropertyChanged("Id_acceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Process_AccesoSoapChannel : Process_APP_Desk.ServiceProcess_Acceso.Process_AccesoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Process_AccesoSoapClient : System.ServiceModel.ClientBase<Process_APP_Desk.ServiceProcess_Acceso.Process_AccesoSoap>, Process_APP_Desk.ServiceProcess_Acceso.Process_AccesoSoap {
        
        public Process_AccesoSoapClient() {
        }
        
        public Process_AccesoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Process_AccesoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_AccesoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_AccesoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet TraerAccesoSinEntidad_Escritorio(int _id_acceso) {
            return base.Channel.TraerAccesoSinEntidad_Escritorio(_id_acceso);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerAccesoSinEntidad_EscritorioAsync(int _id_acceso) {
            return base.Channel.TraerAccesoSinEntidad_EscritorioAsync(_id_acceso);
        }
        
        public Process_APP_Desk.ServiceProcess_Acceso.Acceso TraerAccesoConEntidad_Escritorio(int _id_acceso) {
            return base.Channel.TraerAccesoConEntidad_Escritorio(_id_acceso);
        }
        
        public System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_Acceso.Acceso> TraerAccesoConEntidad_EscritorioAsync(int _id_acceso) {
            return base.Channel.TraerAccesoConEntidad_EscritorioAsync(_id_acceso);
        }
        
        public System.Data.DataSet TraerTodasAccesos_Escritorio() {
            return base.Channel.TraerTodasAccesos_Escritorio();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerTodasAccesos_EscritorioAsync() {
            return base.Channel.TraerTodasAccesos_EscritorioAsync();
        }
    }
}
