//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Process_APP_Desk.ServiceProcess_CargosUsuarios {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProcess_CargosUsuarios.Process_CargosUsuariosSoap")]
    public interface Process_CargosUsuariosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCargosUsuarioSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertarCargosUsuarioSinEntidad_Escritorio(string _rut_usuario, int _id_cargo, int _estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCargosUsuarioSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertarCargosUsuarioSinEntidad_EscritorioAsync(string _rut_usuario, int _id_cargo, int _estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCargosUsuarioSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ActualizarCargosUsuarioSinEntidad_Escritorio(string _rut_usuario, int _id_cargo, int _estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCargosUsuarioSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ActualizarCargosUsuarioSinEntidad_EscritorioAsync(string _rut_usuario, int _id_cargo, int _estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCargosUsuarioPorRutPorCargoSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerCargosUsuarioPorRutPorCargoSinEntidad_Escritorio(string _rut_usuario, int _id_cargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCargosUsuarioPorRutPorCargoSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerCargosUsuarioPorRutPorCargoSinEntidad_EscritorioAsync(string _rut_usuario, int _id_cargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCargosUsuarioPorRutSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerCargosUsuarioPorRutSinEntidad_Escritorio(string _rut_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCargosUsuarioPorRutSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerCargosUsuarioPorRutSinEntidad_EscritorioAsync(string _rut_usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Process_CargosUsuariosSoapChannel : Process_APP_Desk.ServiceProcess_CargosUsuarios.Process_CargosUsuariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Process_CargosUsuariosSoapClient : System.ServiceModel.ClientBase<Process_APP_Desk.ServiceProcess_CargosUsuarios.Process_CargosUsuariosSoap>, Process_APP_Desk.ServiceProcess_CargosUsuarios.Process_CargosUsuariosSoap {
        
        public Process_CargosUsuariosSoapClient() {
        }
        
        public Process_CargosUsuariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Process_CargosUsuariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_CargosUsuariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_CargosUsuariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertarCargosUsuarioSinEntidad_Escritorio(string _rut_usuario, int _id_cargo, int _estado) {
            return base.Channel.InsertarCargosUsuarioSinEntidad_Escritorio(_rut_usuario, _id_cargo, _estado);
        }
        
        public System.Threading.Tasks.Task<int> InsertarCargosUsuarioSinEntidad_EscritorioAsync(string _rut_usuario, int _id_cargo, int _estado) {
            return base.Channel.InsertarCargosUsuarioSinEntidad_EscritorioAsync(_rut_usuario, _id_cargo, _estado);
        }
        
        public int ActualizarCargosUsuarioSinEntidad_Escritorio(string _rut_usuario, int _id_cargo, int _estado) {
            return base.Channel.ActualizarCargosUsuarioSinEntidad_Escritorio(_rut_usuario, _id_cargo, _estado);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarCargosUsuarioSinEntidad_EscritorioAsync(string _rut_usuario, int _id_cargo, int _estado) {
            return base.Channel.ActualizarCargosUsuarioSinEntidad_EscritorioAsync(_rut_usuario, _id_cargo, _estado);
        }
        
        public System.Data.DataSet TraerCargosUsuarioPorRutPorCargoSinEntidad_Escritorio(string _rut_usuario, int _id_cargo) {
            return base.Channel.TraerCargosUsuarioPorRutPorCargoSinEntidad_Escritorio(_rut_usuario, _id_cargo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerCargosUsuarioPorRutPorCargoSinEntidad_EscritorioAsync(string _rut_usuario, int _id_cargo) {
            return base.Channel.TraerCargosUsuarioPorRutPorCargoSinEntidad_EscritorioAsync(_rut_usuario, _id_cargo);
        }
        
        public System.Data.DataSet TraerCargosUsuarioPorRutSinEntidad_Escritorio(string _rut_usuario) {
            return base.Channel.TraerCargosUsuarioPorRutSinEntidad_Escritorio(_rut_usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerCargosUsuarioPorRutSinEntidad_EscritorioAsync(string _rut_usuario) {
            return base.Channel.TraerCargosUsuarioPorRutSinEntidad_EscritorioAsync(_rut_usuario);
        }
    }
}
