//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Process_APP_Desk.ServiceProcess_UsuarioEquipo {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProcess_UsuarioEquipo.Process_UsuarioEquipoSoap")]
    public interface Process_UsuarioEquipoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarUsuarioEquipoSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertarUsuarioEquipoSinEntidad_Escritorio(string _rut_usuario, int _id_equipo, int _responsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarUsuarioEquipoSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertarUsuarioEquipoSinEntidad_EscritorioAsync(string _rut_usuario, int _id_equipo, int _responsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuarioEquipoSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ActualizarUsuarioEquipoSinEntidad_Escritorio(string _rut_usuario, int _id_equipo, int _responsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuarioEquipoSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ActualizarUsuarioEquipoSinEntidad_EscritorioAsync(string _rut_usuario, int _id_equipo, int _responsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerUsuarioEquiPorEquipoPorRutConEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Process_APP_Desk.ServiceProcess_UsuarioEquipo.UsuarioEquipo TraerUsuarioEquiPorEquipoPorRutConEntidad_Escritorio(int _id_equipo, string _rut_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerUsuarioEquiPorEquipoPorRutConEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_UsuarioEquipo.UsuarioEquipo> TraerUsuarioEquiPorEquipoPorRutConEntidad_EscritorioAsync(int _id_equipo, string _rut_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerUsuarioEquipoSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerUsuarioEquipoSinEntidad_Escritorio(int _id_equipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerUsuarioEquipoSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerUsuarioEquipoSinEntidad_EscritorioAsync(int _id_equipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuarioEquipoSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EliminarUsuarioEquipoSinEntidad_Escritorio(int _id_equipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuarioEquipoSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> EliminarUsuarioEquipoSinEntidad_EscritorioAsync(int _id_equipo);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuarioEquipo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int rut_usuarioField;
        
        private int id_equipoField;
        
        private int responsableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Rut_usuario {
            get {
                return this.rut_usuarioField;
            }
            set {
                this.rut_usuarioField = value;
                this.RaisePropertyChanged("Rut_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Id_equipo {
            get {
                return this.id_equipoField;
            }
            set {
                this.id_equipoField = value;
                this.RaisePropertyChanged("Id_equipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Responsable {
            get {
                return this.responsableField;
            }
            set {
                this.responsableField = value;
                this.RaisePropertyChanged("Responsable");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Process_UsuarioEquipoSoapChannel : Process_APP_Desk.ServiceProcess_UsuarioEquipo.Process_UsuarioEquipoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Process_UsuarioEquipoSoapClient : System.ServiceModel.ClientBase<Process_APP_Desk.ServiceProcess_UsuarioEquipo.Process_UsuarioEquipoSoap>, Process_APP_Desk.ServiceProcess_UsuarioEquipo.Process_UsuarioEquipoSoap {
        
        public Process_UsuarioEquipoSoapClient() {
        }
        
        public Process_UsuarioEquipoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Process_UsuarioEquipoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_UsuarioEquipoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_UsuarioEquipoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertarUsuarioEquipoSinEntidad_Escritorio(string _rut_usuario, int _id_equipo, int _responsable) {
            return base.Channel.InsertarUsuarioEquipoSinEntidad_Escritorio(_rut_usuario, _id_equipo, _responsable);
        }
        
        public System.Threading.Tasks.Task<int> InsertarUsuarioEquipoSinEntidad_EscritorioAsync(string _rut_usuario, int _id_equipo, int _responsable) {
            return base.Channel.InsertarUsuarioEquipoSinEntidad_EscritorioAsync(_rut_usuario, _id_equipo, _responsable);
        }
        
        public int ActualizarUsuarioEquipoSinEntidad_Escritorio(string _rut_usuario, int _id_equipo, int _responsable) {
            return base.Channel.ActualizarUsuarioEquipoSinEntidad_Escritorio(_rut_usuario, _id_equipo, _responsable);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarUsuarioEquipoSinEntidad_EscritorioAsync(string _rut_usuario, int _id_equipo, int _responsable) {
            return base.Channel.ActualizarUsuarioEquipoSinEntidad_EscritorioAsync(_rut_usuario, _id_equipo, _responsable);
        }
        
        public Process_APP_Desk.ServiceProcess_UsuarioEquipo.UsuarioEquipo TraerUsuarioEquiPorEquipoPorRutConEntidad_Escritorio(int _id_equipo, string _rut_usuario) {
            return base.Channel.TraerUsuarioEquiPorEquipoPorRutConEntidad_Escritorio(_id_equipo, _rut_usuario);
        }
        
        public System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_UsuarioEquipo.UsuarioEquipo> TraerUsuarioEquiPorEquipoPorRutConEntidad_EscritorioAsync(int _id_equipo, string _rut_usuario) {
            return base.Channel.TraerUsuarioEquiPorEquipoPorRutConEntidad_EscritorioAsync(_id_equipo, _rut_usuario);
        }
        
        public System.Data.DataSet TraerUsuarioEquipoSinEntidad_Escritorio(int _id_equipo) {
            return base.Channel.TraerUsuarioEquipoSinEntidad_Escritorio(_id_equipo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerUsuarioEquipoSinEntidad_EscritorioAsync(int _id_equipo) {
            return base.Channel.TraerUsuarioEquipoSinEntidad_EscritorioAsync(_id_equipo);
        }
        
        public int EliminarUsuarioEquipoSinEntidad_Escritorio(int _id_equipo) {
            return base.Channel.EliminarUsuarioEquipoSinEntidad_Escritorio(_id_equipo);
        }
        
        public System.Threading.Tasks.Task<int> EliminarUsuarioEquipoSinEntidad_EscritorioAsync(int _id_equipo) {
            return base.Channel.EliminarUsuarioEquipoSinEntidad_EscritorioAsync(_id_equipo);
        }
    }
}
