//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Process_APP_Desk.ServiceProcess_Permisos {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProcess_Permisos.Process_PermisosSoap")]
    public interface Process_PermisosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarPermisosSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertarPermisosSinEntidad_Escritorio(int _id_acceso, int _rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarPermisosSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertarPermisosSinEntidad_EscritorioAsync(int _id_acceso, int _rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarPermisosSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ActualizarPermisosSinEntidad_Escritorio(int _id_acceso, int _rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarPermisosSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ActualizarPermisosSinEntidad_EscritorioAsync(int _id_acceso, int _rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerPermisosPorAccesoPorRolSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerPermisosPorAccesoPorRolSinEntidad_Escritorio(int _id_acceso, int _rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerPermisosPorAccesoPorRolSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerPermisosPorAccesoPorRolSinEntidad_EscritorioAsync(int _id_acceso, int _rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerPermisosPorRolSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerPermisosPorRolSinEntidad_Escritorio(int _rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerPermisosPorRolSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerPermisosPorRolSinEntidad_EscritorioAsync(int _rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerPermisosPorRolConEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Process_APP_Desk.ServiceProcess_Permisos.Permisos TraerPermisosPorRolConEntidad_Escritorio(int _id_rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerPermisosPorRolConEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_Permisos.Permisos> TraerPermisosPorRolConEntidad_EscritorioAsync(int _id_rol);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Permisos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_accesoField;
        
        private int id_rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id_acceso {
            get {
                return this.id_accesoField;
            }
            set {
                this.id_accesoField = value;
                this.RaisePropertyChanged("Id_acceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Id_rol {
            get {
                return this.id_rolField;
            }
            set {
                this.id_rolField = value;
                this.RaisePropertyChanged("Id_rol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Process_PermisosSoapChannel : Process_APP_Desk.ServiceProcess_Permisos.Process_PermisosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Process_PermisosSoapClient : System.ServiceModel.ClientBase<Process_APP_Desk.ServiceProcess_Permisos.Process_PermisosSoap>, Process_APP_Desk.ServiceProcess_Permisos.Process_PermisosSoap {
        
        public Process_PermisosSoapClient() {
        }
        
        public Process_PermisosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Process_PermisosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_PermisosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_PermisosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertarPermisosSinEntidad_Escritorio(int _id_acceso, int _rol) {
            return base.Channel.InsertarPermisosSinEntidad_Escritorio(_id_acceso, _rol);
        }
        
        public System.Threading.Tasks.Task<int> InsertarPermisosSinEntidad_EscritorioAsync(int _id_acceso, int _rol) {
            return base.Channel.InsertarPermisosSinEntidad_EscritorioAsync(_id_acceso, _rol);
        }
        
        public int ActualizarPermisosSinEntidad_Escritorio(int _id_acceso, int _rol) {
            return base.Channel.ActualizarPermisosSinEntidad_Escritorio(_id_acceso, _rol);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarPermisosSinEntidad_EscritorioAsync(int _id_acceso, int _rol) {
            return base.Channel.ActualizarPermisosSinEntidad_EscritorioAsync(_id_acceso, _rol);
        }
        
        public System.Data.DataSet TraerPermisosPorAccesoPorRolSinEntidad_Escritorio(int _id_acceso, int _rol) {
            return base.Channel.TraerPermisosPorAccesoPorRolSinEntidad_Escritorio(_id_acceso, _rol);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerPermisosPorAccesoPorRolSinEntidad_EscritorioAsync(int _id_acceso, int _rol) {
            return base.Channel.TraerPermisosPorAccesoPorRolSinEntidad_EscritorioAsync(_id_acceso, _rol);
        }
        
        public System.Data.DataSet TraerPermisosPorRolSinEntidad_Escritorio(int _rol) {
            return base.Channel.TraerPermisosPorRolSinEntidad_Escritorio(_rol);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerPermisosPorRolSinEntidad_EscritorioAsync(int _rol) {
            return base.Channel.TraerPermisosPorRolSinEntidad_EscritorioAsync(_rol);
        }
        
        public Process_APP_Desk.ServiceProcess_Permisos.Permisos TraerPermisosPorRolConEntidad_Escritorio(int _id_rol) {
            return base.Channel.TraerPermisosPorRolConEntidad_Escritorio(_id_rol);
        }
        
        public System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_Permisos.Permisos> TraerPermisosPorRolConEntidad_EscritorioAsync(int _id_rol) {
            return base.Channel.TraerPermisosPorRolConEntidad_EscritorioAsync(_id_rol);
        }
    }
}
