//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Process_APP_Desk.ServiceProcess_Validadores {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProcess_Validadores.Process_ValidadoresSoap")]
    public interface Process_ValidadoresSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/numeroValidacionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool numeroValidacionService(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/numeroValidacionService", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> numeroValidacionServiceAsync(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rutValidacionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool rutValidacionService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rutValidacionService", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> rutValidacionServiceAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/correoValidacionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool correoValidacionService(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/correoValidacionService", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> correoValidacionServiceAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Process_ValidadoresSoapChannel : Process_APP_Desk.ServiceProcess_Validadores.Process_ValidadoresSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Process_ValidadoresSoapClient : System.ServiceModel.ClientBase<Process_APP_Desk.ServiceProcess_Validadores.Process_ValidadoresSoap>, Process_APP_Desk.ServiceProcess_Validadores.Process_ValidadoresSoap {
        
        public Process_ValidadoresSoapClient() {
        }
        
        public Process_ValidadoresSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Process_ValidadoresSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_ValidadoresSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_ValidadoresSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool numeroValidacionService(string num) {
            return base.Channel.numeroValidacionService(num);
        }
        
        public System.Threading.Tasks.Task<bool> numeroValidacionServiceAsync(string num) {
            return base.Channel.numeroValidacionServiceAsync(num);
        }
        
        public bool rutValidacionService(string rut) {
            return base.Channel.rutValidacionService(rut);
        }
        
        public System.Threading.Tasks.Task<bool> rutValidacionServiceAsync(string rut) {
            return base.Channel.rutValidacionServiceAsync(rut);
        }
        
        public bool correoValidacionService(string email) {
            return base.Channel.correoValidacionService(email);
        }
        
        public System.Threading.Tasks.Task<bool> correoValidacionServiceAsync(string email) {
            return base.Channel.correoValidacionServiceAsync(email);
        }
    }
}
