//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Process_APP_Desk.ServiceProcess_Provincia {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProcess_Provincia.Process_ProvinciaSoap")]
    public interface Process_ProvinciaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerProvinciaSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerProvinciaSinEntidad_Escritorio(int _id_provincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerProvinciaSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerProvinciaSinEntidad_EscritorioAsync(int _id_provincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerProvinciaConEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Process_APP_Desk.ServiceProcess_Provincia.Provincia TraerProvinciaConEntidad_Escritorio(int _id_provincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerProvinciaConEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_Provincia.Provincia> TraerProvinciaConEntidad_EscritorioAsync(int _id_provincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerTodasProvinciasPorRegion_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerTodasProvinciasPorRegion_Escritorio(int _id_region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerTodasProvinciasPorRegion_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerTodasProvinciasPorRegion_EscritorioAsync(int _id_region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerTodasProvincias_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerTodasProvincias_Escritorio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerTodasProvincias_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerTodasProvincias_EscritorioAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Provincia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_provinciaField;
        
        private string nombreField;
        
        private int id_regionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id_provincia {
            get {
                return this.id_provinciaField;
            }
            set {
                this.id_provinciaField = value;
                this.RaisePropertyChanged("Id_provincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Id_region {
            get {
                return this.id_regionField;
            }
            set {
                this.id_regionField = value;
                this.RaisePropertyChanged("Id_region");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Process_ProvinciaSoapChannel : Process_APP_Desk.ServiceProcess_Provincia.Process_ProvinciaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Process_ProvinciaSoapClient : System.ServiceModel.ClientBase<Process_APP_Desk.ServiceProcess_Provincia.Process_ProvinciaSoap>, Process_APP_Desk.ServiceProcess_Provincia.Process_ProvinciaSoap {
        
        public Process_ProvinciaSoapClient() {
        }
        
        public Process_ProvinciaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Process_ProvinciaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_ProvinciaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_ProvinciaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet TraerProvinciaSinEntidad_Escritorio(int _id_provincia) {
            return base.Channel.TraerProvinciaSinEntidad_Escritorio(_id_provincia);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerProvinciaSinEntidad_EscritorioAsync(int _id_provincia) {
            return base.Channel.TraerProvinciaSinEntidad_EscritorioAsync(_id_provincia);
        }
        
        public Process_APP_Desk.ServiceProcess_Provincia.Provincia TraerProvinciaConEntidad_Escritorio(int _id_provincia) {
            return base.Channel.TraerProvinciaConEntidad_Escritorio(_id_provincia);
        }
        
        public System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_Provincia.Provincia> TraerProvinciaConEntidad_EscritorioAsync(int _id_provincia) {
            return base.Channel.TraerProvinciaConEntidad_EscritorioAsync(_id_provincia);
        }
        
        public System.Data.DataSet TraerTodasProvinciasPorRegion_Escritorio(int _id_region) {
            return base.Channel.TraerTodasProvinciasPorRegion_Escritorio(_id_region);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerTodasProvinciasPorRegion_EscritorioAsync(int _id_region) {
            return base.Channel.TraerTodasProvinciasPorRegion_EscritorioAsync(_id_region);
        }
        
        public System.Data.DataSet TraerTodasProvincias_Escritorio() {
            return base.Channel.TraerTodasProvincias_Escritorio();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerTodasProvincias_EscritorioAsync() {
            return base.Channel.TraerTodasProvincias_EscritorioAsync();
        }
    }
}
