//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Process_APP_Desk.ServiceProcess_Usuario {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProcess_Usuario.Process_UsuarioSoap")]
    public interface Process_UsuarioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarUsuarioConEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertarUsuarioConEntidad_Escritorio(System.Data.DataSet _unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarUsuarioConEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertarUsuarioConEntidad_EscritorioAsync(System.Data.DataSet _unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarUsuarioSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertarUsuarioSinEntidad_Escritorio(string _rut_usuario, string _primer_nombre, string _segundo_nombre, string _primer_apellido, string _segundo_apellido, string _direccion, string _correo, int _telefono_fijp, int _telefono_movil, int _estado, int _id_comuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarUsuarioSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertarUsuarioSinEntidad_EscritorioAsync(string _rut_usuario, string _primer_nombre, string _segundo_nombre, string _primer_apellido, string _segundo_apellido, string _direccion, string _correo, int _telefono_fijp, int _telefono_movil, int _estado, int _id_comuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuarioConEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ActualizarUsuarioConEntidad_Escritorio(System.Data.DataSet _unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuarioConEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ActualizarUsuarioConEntidad_EscritorioAsync(System.Data.DataSet _unidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuarioSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ActualizarUsuarioSinEntidad_Escritorio(string _rut_usuario, string _primer_nombre, string _segundo_nombre, string _primer_apellido, string _segundo_apellido, string _direccion, string _correo, int _telefono_fijp, int _telefono_movil, int _estado, int _id_comuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuarioSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ActualizarUsuarioSinEntidad_EscritorioAsync(string _rut_usuario, string _primer_nombre, string _segundo_nombre, string _primer_apellido, string _segundo_apellido, string _direccion, string _correo, int _telefono_fijp, int _telefono_movil, int _estado, int _id_comuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerUsuarioSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerUsuarioSinEntidad_Escritorio(string _rut_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerUsuarioSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerUsuarioSinEntidad_EscritorioAsync(string _rut_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerUsuarioConEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Process_APP_Desk.ServiceProcess_Usuario.Usuario TraerUsuarioConEntidad_Escritorio(string _rut_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerUsuarioConEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_Usuario.Usuario> TraerUsuarioConEntidad_EscritorioAsync(string _rut_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerTodasUsuarios_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerTodasUsuarios_Escritorio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerTodasUsuarios_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerTodasUsuarios_EscritorioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerUsuarioPorRutPorEmpresaSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerUsuarioPorRutPorEmpresaSinEntidad_Escritorio(string _rut_usuario, string _rut_empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerUsuarioPorRutPorEmpresaSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerUsuarioPorRutPorEmpresaSinEntidad_EscritorioAsync(string _rut_usuario, string _rut_empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerTodasUsuariosJoin_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerTodasUsuariosJoin_Escritorio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerTodasUsuariosJoin_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerTodasUsuariosJoin_EscritorioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerUsuarioConClaveSinEntidad_Escritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TraerUsuarioConClaveSinEntidad_Escritorio(string _palabra_clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerUsuarioConClaveSinEntidad_Escritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TraerUsuarioConClaveSinEntidad_EscritorioAsync(string _palabra_clave);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rut_usuarioField;
        
        private string primer_nombreField;
        
        private string segundo_nombreField;
        
        private string primer_apellidoField;
        
        private string segundo_apellidoField;
        
        private string direccionField;
        
        private string correoField;
        
        private int telefono_fijoField;
        
        private int telefono_movilField;
        
        private int estadoField;
        
        private int id_comunaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Rut_usuario {
            get {
                return this.rut_usuarioField;
            }
            set {
                this.rut_usuarioField = value;
                this.RaisePropertyChanged("Rut_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Primer_nombre {
            get {
                return this.primer_nombreField;
            }
            set {
                this.primer_nombreField = value;
                this.RaisePropertyChanged("Primer_nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Segundo_nombre {
            get {
                return this.segundo_nombreField;
            }
            set {
                this.segundo_nombreField = value;
                this.RaisePropertyChanged("Segundo_nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Primer_apellido {
            get {
                return this.primer_apellidoField;
            }
            set {
                this.primer_apellidoField = value;
                this.RaisePropertyChanged("Primer_apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Segundo_apellido {
            get {
                return this.segundo_apellidoField;
            }
            set {
                this.segundo_apellidoField = value;
                this.RaisePropertyChanged("Segundo_apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("Correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Telefono_fijo {
            get {
                return this.telefono_fijoField;
            }
            set {
                this.telefono_fijoField = value;
                this.RaisePropertyChanged("Telefono_fijo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Telefono_movil {
            get {
                return this.telefono_movilField;
            }
            set {
                this.telefono_movilField = value;
                this.RaisePropertyChanged("Telefono_movil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int Id_comuna {
            get {
                return this.id_comunaField;
            }
            set {
                this.id_comunaField = value;
                this.RaisePropertyChanged("Id_comuna");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Process_UsuarioSoapChannel : Process_APP_Desk.ServiceProcess_Usuario.Process_UsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Process_UsuarioSoapClient : System.ServiceModel.ClientBase<Process_APP_Desk.ServiceProcess_Usuario.Process_UsuarioSoap>, Process_APP_Desk.ServiceProcess_Usuario.Process_UsuarioSoap {
        
        public Process_UsuarioSoapClient() {
        }
        
        public Process_UsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Process_UsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_UsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Process_UsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertarUsuarioConEntidad_Escritorio(System.Data.DataSet _unidad) {
            return base.Channel.InsertarUsuarioConEntidad_Escritorio(_unidad);
        }
        
        public System.Threading.Tasks.Task<int> InsertarUsuarioConEntidad_EscritorioAsync(System.Data.DataSet _unidad) {
            return base.Channel.InsertarUsuarioConEntidad_EscritorioAsync(_unidad);
        }
        
        public int InsertarUsuarioSinEntidad_Escritorio(string _rut_usuario, string _primer_nombre, string _segundo_nombre, string _primer_apellido, string _segundo_apellido, string _direccion, string _correo, int _telefono_fijp, int _telefono_movil, int _estado, int _id_comuna) {
            return base.Channel.InsertarUsuarioSinEntidad_Escritorio(_rut_usuario, _primer_nombre, _segundo_nombre, _primer_apellido, _segundo_apellido, _direccion, _correo, _telefono_fijp, _telefono_movil, _estado, _id_comuna);
        }
        
        public System.Threading.Tasks.Task<int> InsertarUsuarioSinEntidad_EscritorioAsync(string _rut_usuario, string _primer_nombre, string _segundo_nombre, string _primer_apellido, string _segundo_apellido, string _direccion, string _correo, int _telefono_fijp, int _telefono_movil, int _estado, int _id_comuna) {
            return base.Channel.InsertarUsuarioSinEntidad_EscritorioAsync(_rut_usuario, _primer_nombre, _segundo_nombre, _primer_apellido, _segundo_apellido, _direccion, _correo, _telefono_fijp, _telefono_movil, _estado, _id_comuna);
        }
        
        public int ActualizarUsuarioConEntidad_Escritorio(System.Data.DataSet _unidad) {
            return base.Channel.ActualizarUsuarioConEntidad_Escritorio(_unidad);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarUsuarioConEntidad_EscritorioAsync(System.Data.DataSet _unidad) {
            return base.Channel.ActualizarUsuarioConEntidad_EscritorioAsync(_unidad);
        }
        
        public int ActualizarUsuarioSinEntidad_Escritorio(string _rut_usuario, string _primer_nombre, string _segundo_nombre, string _primer_apellido, string _segundo_apellido, string _direccion, string _correo, int _telefono_fijp, int _telefono_movil, int _estado, int _id_comuna) {
            return base.Channel.ActualizarUsuarioSinEntidad_Escritorio(_rut_usuario, _primer_nombre, _segundo_nombre, _primer_apellido, _segundo_apellido, _direccion, _correo, _telefono_fijp, _telefono_movil, _estado, _id_comuna);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarUsuarioSinEntidad_EscritorioAsync(string _rut_usuario, string _primer_nombre, string _segundo_nombre, string _primer_apellido, string _segundo_apellido, string _direccion, string _correo, int _telefono_fijp, int _telefono_movil, int _estado, int _id_comuna) {
            return base.Channel.ActualizarUsuarioSinEntidad_EscritorioAsync(_rut_usuario, _primer_nombre, _segundo_nombre, _primer_apellido, _segundo_apellido, _direccion, _correo, _telefono_fijp, _telefono_movil, _estado, _id_comuna);
        }
        
        public System.Data.DataSet TraerUsuarioSinEntidad_Escritorio(string _rut_usuario) {
            return base.Channel.TraerUsuarioSinEntidad_Escritorio(_rut_usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerUsuarioSinEntidad_EscritorioAsync(string _rut_usuario) {
            return base.Channel.TraerUsuarioSinEntidad_EscritorioAsync(_rut_usuario);
        }
        
        public Process_APP_Desk.ServiceProcess_Usuario.Usuario TraerUsuarioConEntidad_Escritorio(string _rut_usuario) {
            return base.Channel.TraerUsuarioConEntidad_Escritorio(_rut_usuario);
        }
        
        public System.Threading.Tasks.Task<Process_APP_Desk.ServiceProcess_Usuario.Usuario> TraerUsuarioConEntidad_EscritorioAsync(string _rut_usuario) {
            return base.Channel.TraerUsuarioConEntidad_EscritorioAsync(_rut_usuario);
        }
        
        public System.Data.DataSet TraerTodasUsuarios_Escritorio() {
            return base.Channel.TraerTodasUsuarios_Escritorio();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerTodasUsuarios_EscritorioAsync() {
            return base.Channel.TraerTodasUsuarios_EscritorioAsync();
        }
        
        public System.Data.DataSet TraerUsuarioPorRutPorEmpresaSinEntidad_Escritorio(string _rut_usuario, string _rut_empresa) {
            return base.Channel.TraerUsuarioPorRutPorEmpresaSinEntidad_Escritorio(_rut_usuario, _rut_empresa);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerUsuarioPorRutPorEmpresaSinEntidad_EscritorioAsync(string _rut_usuario, string _rut_empresa) {
            return base.Channel.TraerUsuarioPorRutPorEmpresaSinEntidad_EscritorioAsync(_rut_usuario, _rut_empresa);
        }
        
        public System.Data.DataSet TraerTodasUsuariosJoin_Escritorio() {
            return base.Channel.TraerTodasUsuariosJoin_Escritorio();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerTodasUsuariosJoin_EscritorioAsync() {
            return base.Channel.TraerTodasUsuariosJoin_EscritorioAsync();
        }
        
        public System.Data.DataSet TraerUsuarioConClaveSinEntidad_Escritorio(string _palabra_clave) {
            return base.Channel.TraerUsuarioConClaveSinEntidad_Escritorio(_palabra_clave);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TraerUsuarioConClaveSinEntidad_EscritorioAsync(string _palabra_clave) {
            return base.Channel.TraerUsuarioConClaveSinEntidad_EscritorioAsync(_palabra_clave);
        }
    }
}
